export const enum SVLLayerState {
    UNINITIALIZED,
    INITIALIZED,
    VISIBLE,
    DRAWING_ABORTED,
    AUTOMATICALLY_DISABLED,
    USER_DISABLED
}

// These events are accepted by the mediator from controllers. Then the mediator decides what to do (probably, firing a SVLEvent)
export const enum AcceptedControllerEvents {
    PREFERENCES_EXPORT_REQUEST = 'PREFERENCES_EXPORT_REQUEST',
    PREFERENCES_IMPORT_REQUEST = 'PREFERENCES_IMPORT_REQUEST',
    PREFERENCES_SAVE_REQUEST = 'PREFERENCES_SAVE_REQUEST',
    PREFERENCES_RESET_REQUEST = 'PREFERENCES_RESET_REQUEST',
    PREFERENCES_ROLLBACK_REQUEST = 'PREFERENCES_ROLLBACK_REQUEST',
    REDRAW_ALL_REQUEST = 'REDRAW_ALL_REQUEST',
    PREFERENCES_UI_REQUIRE_REFRESH = 'PREFERENCES_UI_REQUIRE_REFRESH',
    PREFERENCES_UPDATED_REQUIRES_REDRAW = 'PREFERENCES_UPDATED_REQUIRES_REDRAW', //updateStylesFromPreferences
    USER_UPDATED_SVL_PREFERENCES = 'USER_UPDATED_SVL_PREFERENCES',
    WME_SETTINGS_UPDATED = 'WME_SETTINGS_UPDATED',
    SVL_SHOULD_AUTOMATICALLY_DISABLE = 'SVL_SHOULD_AUTOMATICALLY_DISABLE',
    SVL_DRAWING_WAS_ABORTED = 'SVL_DRAWING_WAS_ABORTED',
    SVL_LAYER_ENABLED = 'SVL_LAYER_ENABLED',
    SVL_LAYER_DISABLED = 'SVL_LAYER_DISABLED',
    COUNTRY_CHANGED = 'COUNTRY_CHANGED',
    FIRST_RUN = 'FIRST_RUN'
}

export const SDK_LAYERS = {
    SEGMENTS: "Street Vector Layer (SVL)",
    ARROWS: "SVL_ARROWS_SDK",
    NODES: "SVL_NODES_SDK",
    //LABELS: "SVL_LABELS_SDK",
    ICONS: "SVL_ICONS_SDK" // e.g. average speed cameras
};

export const OL_LAYERS = {
    LABELS: "vectorLabels"
};